lib: [
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/META" {"META"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/dune-package" {"dune-package"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/IrminWeb.a" {"lib/IrminWeb.a"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/IrminWeb.cma" {"lib/IrminWeb.cma"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/IrminWeb.cmxa" {"lib/IrminWeb.cmxa"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/IrminWeb.cmxs" {"lib/IrminWeb.cmxs"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/LocalStorage.re" {"lib/LocalStorage.re"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/LocalStorage.rei" {"lib/LocalStorage.rei"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb.cmi" {"lib/irminWeb.cmi"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb.cmt" {"lib/irminWeb.cmt"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb.cmx" {"lib/irminWeb.cmx"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb.ml" {"lib/irminWeb.ml"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb__LocalStorage.cmi" {"lib/irminWeb__LocalStorage.cmi"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb__LocalStorage.cmt" {"lib/irminWeb__LocalStorage.cmt"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb__LocalStorage.cmti" {"lib/irminWeb__LocalStorage.cmti"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/lib/irminWeb__LocalStorage.cmx" {"lib/irminWeb__LocalStorage.cmx"}
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/lib/irmin-web/opam" {"opam"}
]
bin: [
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/bin/IrminWebApp.exe" {"IrminWebApp.exe"}
]
doc: [
  "/home/aweis/irmin-web/_esy/default/store/b/irmin_web-c9a46e92/install/default/doc/irmin-web/README.md"
]
